version: '3.8'

services:
  db:
    image: postgres:15.1-alpine
    restart: on-failure
    env_file:
      - .env
    ports:
      - "${POSTGRES_PORT}:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d ${POSTGRES_DB} -U ${POSTGRES_USER}" ]
      interval: 5s
      timeout: 20s
      retries: 100
    networks:
      custom:

  cache:
    image: redis:latest
    restart: on-failure
    env_file:
      - .env
    volumes:
      - redis_data:/data
    ports:
      - "${REDIS_PORT}:6379"
    networks:
      custom:

  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: prod
    container_name: fastapi-app
    restart: on-failure
    ports:
      - "${APP_PORT}:8000"
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
      cache:
        condition: service_started
    networks:
      custom:

networks:
  custom:
    driver: bridge

volumes:
  redis_data: