version: '3.8'

services:
  test_db:
    image: postgres:15.1-alpine
    restart: on-failure
    env_file:
      - .env
    environment:
      POSTGRES_DB: "${POSTGRES_DB2}"
    ports:
      - "${POSTGRES_TEST_PORT}:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d ${POSTGRES_DB2} -U ${POSTGRES_USER}" ]
      interval: 5s
      timeout: 20s
      retries: 100
    networks:
      custom_test:

  app-test:
    build:
      context: .
      dockerfile: Dockerfile
      target: test
    container_name: fastapi-app-test
    ports:
      - "${APP_PORT_TEST}:8000"
    env_file:
      - .env
    environment:
      - TEST=1
    depends_on:
      test_db:
        condition: service_healthy
    networks:
      custom_test:

networks:
  custom_test:
    driver: bridge